---
- hosts: ws
  become: true
  ignore_errors: true
  gather_facts: true
  # Uncomment if needed: become_user: root
  vars:
    package_name: httpd

  tasks:
    - name: install package
      yum:
        name: "{{ package_name }}"
        state: present

    - name: Create multiple groups
      group:
        name: "{{ item }}"
        state: present
      loop:
        - cloud
        - security
        - devops
        - linuxsa
       